// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFBAP3Yk855KYQUKHABmM6IitM0Fe4G-I',
    appId: '1:388658963553:web:3fbafe9dfc79fd63797620',
    messagingSenderId: '388658963553',
    projectId: 'sentimentanalysis-4e24f',
    authDomain: 'sentimentanalysis-4e24f.firebaseapp.com',
    storageBucket: 'sentimentanalysis-4e24f.appspot.com',
    measurementId: 'G-HTTDN889LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtF5HMM7V-PSZAHvMbv8V3SexQa5Y6_y4',
    appId: '1:388658963553:android:0d65498889937827797620',
    messagingSenderId: '388658963553',
    projectId: 'sentimentanalysis-4e24f',
    storageBucket: 'sentimentanalysis-4e24f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBusE2s1y8EiPmtXyU2CvHsb8DdKKM_g',
    appId: '1:388658963553:ios:3ff34f6d0f8a214f797620',
    messagingSenderId: '388658963553',
    projectId: 'sentimentanalysis-4e24f',
    storageBucket: 'sentimentanalysis-4e24f.appspot.com',
    iosClientId: '388658963553-6f836121kb33bblia8s1ggrjf29d8vk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentimentanalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALBusE2s1y8EiPmtXyU2CvHsb8DdKKM_g',
    appId: '1:388658963553:ios:3ff34f6d0f8a214f797620',
    messagingSenderId: '388658963553',
    projectId: 'sentimentanalysis-4e24f',
    storageBucket: 'sentimentanalysis-4e24f.appspot.com',
    iosClientId: '388658963553-6f836121kb33bblia8s1ggrjf29d8vk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentimentanalysis',
  );
}
